sudo: false
language: rust

rust:
  - 1.18.0
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo check --no-default-features

matrix:
  include:
    - rust: 1.15.0
      script:
        - cargo build
        - cargo build --no-default-features
