sudo: false
language: rust

rust:
  - 1.18.0
  - stable
  - beta

script:
  - cargo test
  - cargo check --no-default-features

matrix:
  include:
    - rust: nightly
      script:
        - cargo test
        - cargo check --no-default-features
        - cargo check --no-default-features --features alloc
    - rust: 1.15.0
      script:
        - cargo build
        - cargo build --no-default-features
