[package]
name = "serde_bytes"
version = "0.9.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Optimized handling of `&[u8]` and `Vec<u8>` for Serde"
homepage = "https://serde.rs"
repository = "https://github.com/serde-rs/bytes"
documentation = "https://docs.serde.rs/serde_bytes/"
keywords = ["serde", "serialization", "no_std"]
categories = ["encoding"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
publish = false # this branch contains breaking changes

[features]
default = ["std"]
std = ["serde/std"]
collections = ["serde/collections"]

[dependencies]
serde = { git = "https://github.com/serde-rs/serde", branch = "1.0", default-features = false }

[dev-dependencies]
bincode = "=1.0.0-alpha6"
serde_derive = { git = "https://github.com/serde-rs/serde", branch = "1.0" }
serde_test = { git = "https://github.com/serde-rs/serde", branch = "1.0" }
